services:
    db:
        image: postgres:15
        environment:
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: laravel
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - laravel_network
        ports:
            - "5432:5432"

volumes:
    db_data:

networks:
    laravel_network:
        driver: bridge
